### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defineProperty' of undefined

### ISSUE THREAD

**Issue by artemgurzhii** [algonauti/ember-g-recaptcha#12]
I was getting [TypeError: window.grecaptcha.render is not a function #9 ](https://github.com/algonauti/ember-g-recaptcha/issues/9) error, so I have decided to update from `^0.5.0` to `^0.8.0` and after I was getting this error:

`at Module.callback (vendor.js:196560)`

```js
define('ember-g-recaptcha/configuration', ['exports'], function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", { // `Object.defineProperty` throws error
    value: true
  });
  var Object = Ember.Object;
  exports.default = Object.create();
});
```

This probably happens after [this commit](https://github.com/algonauti/ember-g-recaptcha/commit/6f74ec53012a86552d1ecb05cc15395b8b684cad#diff-5227b5b57f04a33e47da355f61574274).

**Comment by mitchiru** [comment]
Same here.

**Comment by algodave** [comment]
@artemgurzhii @mitchiru Are you on Ember 3 at least?

**Comment by mitchiru** [comment]
No. 2.18 or something. I went back to 0.5.0 as I remember.

**Comment by algodave** [comment]
Ok, thank you for reporting. This gave me the chance to put a note on [v0.8.0 release](https://github.com/algonauti/ember-g-recaptcha/releases/tag/v0.8.0) 

I can close this.

**Comment by artemgurzhii** [comment]
@algodave I'm currently facing other problem, as our app is built on the Ember@2.15.0.

When I have tried to update to the `ember-g-recaptcha@0.9.0` I was getting `Cannot read property 'defineProperty' of undefined` and after I have a rollbacked to the `ember-g-recaptcha@0.7.0` I'm getting `TypeError: window.grecaptcha.render is not a function`.

Currently, I can solve this problem by creating `app/components/g-recaptcha.js` file and copying all `renderReCaptcha ` method with only one line changed
```js
if (isNone(window.grecaptcha) || isNone(window.grecaptcha.render)) {
```

Is there any better option to fix this?

**Comment by algodave** [comment]
@artemgurzhii Updated Readme, thanks for the heads up!
