### ISSUE TITLE
 Cannot read property 'defineProperty' of undefined

### ISSUE THREAD

**Issue by BenJohnCarson** [algonauti/ember-g-recaptcha#14]
Hey,
I've just tried updating the addon from 0.4.0 to 0.9.0 and upon loading a page with recaptcha I'm getting  `Cannot read property 'defineProperty' of undefined` error in the console.

After a bit of searching, I found a similar issue raised in ember-cli-qunit: https://github.com/ember-cli/ember-cli-qunit/issues/202. I believe the issue is due to this file: [configuration.js](https://github.com/algonauti/ember-g-recaptcha/blob/master/addon/configuration.js), and it appears to work if I rename the Object import to EmberObject. Not sure if doing this will have any other knock-on effects though.

My app is currently running Ember version 2.15

**Comment by algodave** [comment]
You need to upgrade your Ember version to 3 or above - See #12
