### ISSUE TITLE
Is this add-on dead?

### ISSUE THREAD

**Issue by keanedawg** [algonauti/ember-g-recaptcha#29]
We are bumping our Ember versions from 3.4 to 3.12 when we are being halted by deprecation warnings from this add-on. There appear to be outstanding pull-requests that fix those specified deprecations, but it doesn't look like there has been any original follow-up by the codeowner/codeowners.

**Comment by algodave** [comment]
@keanedawg I'll take care of this soon. Sorry for delay!

**Comment by algodave** [comment]
@keanedawg Released version `1.1.0` and opened #36 for bringing this addon back to life 😃

**Comment by keanedawg** [comment]
Thank you!
