### ISSUE TITLE
Access-Control-Allow-Origin problem

### ISSUE THREAD

**Issue by beastmst** [algonauti/ember-g-recaptcha#4]
is it the only way that using a proxy service to get around the Access-Control-Allow-Origin in chrome?

**Comment by rizkysyazuli** [comment]
Got the same problem. Both from localhost and my staging site. Any idea why?

**Comment by rizkysyazuli** [comment]
After some research, it seems i have to do the verification on the server-side. AJAX just wont work due to CORS limitation.

**Comment by algodave** [comment]
@beastmst @rizkysyazuli There's currently no plan to handle verification of user's response in the scope of this addon. If the CORS issue occurs at such stage, I think we can close this issue
