### ISSUE TITLE
Double GRecaptcha in the same page doesn't work

### ISSUE THREAD

**Issue by musaffa** [algonauti/ember-g-recaptcha#63]
I've been trying to put more more than one GRepatcha in the same page. For this, I set separate ids for each <GRecaptcha ... /> and these id assignments work just fine. But the reference to `this.element` is lost in [this](https://github.com/algonauti/ember-g-recaptcha/blob/0ecdc223fb86f8e1f9ee5134d116f0893fa1fb2a/addon/components/g-recaptcha.js#L74) anonymous callback function and always [resolves](https://github.com/algonauti/ember-g-recaptcha/blob/0ecdc223fb86f8e1f9ee5134d116f0893fa1fb2a/addon/components/g-recaptcha.js#L29) to the element of the last `<GRecaptcha />`. SInce the `grecaptcha.render` is called on the same `this.element` multiple times,  it leads to the error.

**Comment by sinankeskin** [comment]
Hey @musaffa multiple captcha in same page seems unnatural to me. All purpose to validate whether user is a real human being or robot. So, If you need 2nd or more captcha you must destroy the visible one and show the others but one at a time. That's the better approach I believe.

Closing for now. Feel free to reopen if you need.

Thanks for the comment.

**Comment by musaffa** [comment]
Consider this use case. This is the admin login page. Login form has a recaptcha. At the footer, we have email subscription section. It's a common practice to place email subscription at the footer. This footer is available in all the pages. Email subscription section of the footer also has a recaptcha. Thus we have two recaptchas in the same page. This login and footer components live on their own. They don't to know whether the other component is using a recaptcha.

![Screenshot from 2022-03-01 17-48-11](https://user-images.githubusercontent.com/294616/156163915-efa470ea-2a47-4929-8c59-8854c211cd59.png)

Btw, multiple recaptchas in the same page is allowed by Recaptcha.

**Comment by sinankeskin** [comment]
Ok @musaffa got your point. I'll think about something. Thank you.
