### ISSUE TITLE
Error after upgrading to Ember 4.4.0

### ISSUE THREAD

**Issue by kboucher** [algonauti/ember-g-recaptcha#80]
I have been using `ember-g-recaptcha` for quite a while to regulate access to an email form on my Ember 2.* website. I am in the process of upgrading this implementation to Ember 4.4.0, but I am unable to get the `ember-g-recaptcha` `GRecaptcha` component to work in that context.

I receive the following error when trying to render the `GRecaptcha` component (while running locally against the Ember development server):

```
recaptcha__en.js:206 Uncaught Error: Missing required parameters: sitekey
    at Dw.<anonymous> (recaptcha__en.js:206:228)
    at new Dw (recaptcha__en.js:454:222)
    at T6.<anonymous> (recaptcha__en.js:306:483)
    at new T6 (recaptcha__en.js:682:388)
    at Array.<anonymous> (recaptcha__en.js:141:79)
    at recaptcha__en.js:415:279
    at Array.forEach (<anonymous>)
    at Array.<anonymous> (recaptcha__en.js:415:247)
    at Array.<anonymous> (recaptcha__en.js:354:496)
    at Q.<computed>.<computed>.<computed>.Q.<computed>.<computed>.<computed> [as gor] (recaptcha__en.js:133:232)
```

I have the following in my environment.js:

```
    const ENV = {
        // The usual stuff
    };

    ENV['ember-g-recaptcha'] = {
        jsUrl: 'https://www.google.com/recaptcha/api.js?render=explicit', // default
        sitekey: '<my valid Google recaptcha site key>,
    };
```

...and the following in my template (with corresponding `@action` blocks in my Controller):

```
<GRecaptcha
    @onExpired={{this.onCaptchaExpired}}
    @onSuccess={{this.onCaptchaResolved}}
/>
```

I have no idea what I could be missing. Any insight would be greatly appreciated.

**Comment by kboucher** [comment]
Thank you @sinankeskin! That seems to have rectified the issue.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1943568/182396101-63a273e4-5e0c-4d9c-a984-348f82f2f2d5.png">

**Comment by sinankeskin** [comment]
So nice to hear @kboucher
