### ISSUE TITLE
TypeError: window.grecaptcha.render is not a function

### ISSUE THREAD

**Issue by dguayrobotiq** [algonauti/ember-g-recaptcha#9]
Version: `0.4.0`

I got this error in Sentry from an ip in Germany:

`TypeError: window.grecaptcha.render is not a function`

and this is the code (I've put a <---- on the faulty line) from Sentry:

```
var properties = this.getProperties('sitekey', 'theme', 'type', 'size', 'tabindex');
var parameters = _ember['default'].merge(properties, {
callback: this.get('successCallback').bind(this),
  'expired-callback': this.get('expiredCallback').bind(this)
});
var widgetId = window.grecaptcha.render(container, parameters);  <----
this.set('widgetId', widgetId);
this.set('ref', this);
```

from file: `ember-g-recaptcha/components/g-recaptcha.js`

Any idea why that happened?

**Comment by craig2017** [comment]
I had this problem too at 0.4.0.  I think the instructions have changed along the way.  You are probably missing the jsUrl in your env file.  I think the ?render=explicit is critical now.

`var ENV = {
    // ...
 
    gReCaptcha: {
      jsUrl: 'https://www.google.com/recaptcha/api.js?render=explicit', // default
      siteKey: 'your-recaptcha-site-key'
    }
 
    // ...
  }`

**Comment by craig2017** [comment]
Actually, it was working, now it stopped again.  I gave up and added the script tag to my head.
```
  <script src="https://www.google.com/recaptcha/api.js?render=explicit" async></script>
```

**Comment by craig2017** [comment]
Ok, i had some free time today to fix this.  It was just a race condition.  Recaptcha seems to be initializing window.grecaptcha first and then making another call to load the rest of the data.  I can try to do a PR if I'm allowed to fix it.

We just need to check if window.grecaptcha.render is set.
```
renderReCaptcha() {
    if (isNone(window.grecaptcha) || isNone(window.grecaptcha.render)) {
      later(() => {
        this.renderReCaptcha();
      }, 500);
 ```

**Comment by craig2017** [comment]
Maybe... I just patched the existing code by adding ``` || isNone(window.grecaptcha.render```

**Comment by Allerby** [comment]
I'm see this as well when I'm rendering with Fastboot (window is not available on node).

**Comment by algodave** [comment]
A quick fix for this is in https://github.com/algonauti/ember-g-recaptcha/pull/11 so I can close this - thanks @craig2017 👍 

However, a better solution seems to be the one suggested by @cosmosgenius - so I opened #13

**Comment by gabrielsimpsons** [comment]
Make sure your application is not loading multiple times `'https://www.google.com/recaptcha/api.js`
